//AUTH
export const SAVE_SESSION = 'SAVE_SESSION';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_INTEREST = 'GET_INTEREST';
export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';
export const CONFIRM_CODE = 'CONFIRM_CODE';
export const SAVE_INTEREST = 'SAVE_INTEREST';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_SIGNUP = 'GOOGLE_SIGNUP';
export const GOOGLE_FAIL = 'GOOGLE_FAIL';
//ACTIVITY
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const JOIN_ACTIVITY = 'JOIN_ACTIVITY';
export const GET_UPCOMING_ACTIVITY = 'GET_UPCOMING_ACTIVITY';
export const GET_PAST_ACTIVITY = 'GET_PAST_ACTIVITY';
//group
export const CREATE_GROUP = 'CREATE_GROUP';
export const GET_GROUP = 'GET_GROUP';
export const JOIN_GROUP = 'JOIN_GROUP';
export const LEAVE_GROUP = 'LEAVE_GROUP';
export const INVITE_GROUP = 'INVITE_GROUP';
export const RESPOND_INVITE_GROUP = 'RESPOND_INVITE_GROUP';
export const REMOVE_PEOPLE_GROUP = 'REMOVE_PEOPLE_GROUP';
export const SEND_MESSAGE_GROUP = 'SEND_MESSAGE_GROUP';
export const GET_ALL_GROUP = 'GET_ALL_GROUP';
export const GET_ALL_INVITE_GROUP = 'GET_ALL_INVITE_GROUP';
export const GET_ALL_MESSAGE_GROUP = 'GET_ALL_MESSAGE_GROUP';
export const GET_ALL_CHAT_GROUP = 'GET_ALL_CHAT_GROUP';
